spring.application.name=fidelizacion

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/fidelizacion}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console